feat(orchestrator): Only use POST request body parameters
gciavarrini/backstage-plugins pull request #14
Opened 2024-02-28 14:45 UTC by JudeNiroshan

Fix for the below reported bug

JIRA: https://issues.redhat.com/browse/FLPATH-956

2024-02-28 16:23 UTC, gciavarrini requested changes

2024-02-28 16:23 UTC, gciavarrini commented on plugins/orchestrator-backend/src/service/api/v1.ts
>          });
Please don't change v1 implementation.
This change should affect only v2

2024-02-28 16:23 UTC, gciavarrini commented on plugins/orchestrator-backend/src/service/router.ts
> +    await V1.createWorkflow(services.workflowService, uri, workflowDef)
as before, please don't change v1 implementation

2024-02-28 16:23 UTC, gciavarrini commented on plugins/orchestrator-common/src/openapi/openapi.yaml
> +                definition:
Whenever you edit openapi.yaml them you must run ` yarn --cwd plugins/orchestrator-common openapi` (from the root folder) to re-generate auto-generated files (schemas, definitions and doc).

2024-02-28 16:23 UTC, gciavarrini commented on plugins/orchestrator/src/api/OrchestratorClient.ts
> +      body: JSON.stringify(requestBody),
is this change mandatory? or we can somehow handle it in v2.ts ?

2024-02-29 10:16 UTC, JudeNiroshan commented on plugins/orchestrator-backend/src/service/router.ts
> +    await V1.createWorkflow(services.workflowService, uri, workflowDef)
We need to extract the workflow definition obj from the payload. It's the only change done here, other changes have been removed

2024-02-29 10:23 UTC, JudeNiroshan commented on plugins/orchestrator/src/api/OrchestratorClient.ts
> +      body: JSON.stringify(requestBody),
Yes, I wonder how did it work up-until now. Because the payload simply passed from the UI components which I doubt has the required payload structure according to our openapi spec

2024-02-29 13:23 UTC, JudeNiroshan commented
Closing this PR as the `createWorkflow` is still under debate. There is no need for this endpoint at this point in time.

2024-02-29 13:23 UTC, closed without merging